### ISSUE TITLE
Error in extractZip function

### ISSUE THREAD

**Issue by AdrienIT** [Tanguy-Boisset/bloodhound-automation#4]
Hello, got an issue when running the project : 
```
python3 bloodhound-automation.py -h
```

The error : 

```
Traceback (most recent call last):
  File "bloodhound-automation.py", line 8, in <module>
    from src.project import Project
  File "/home/adrien/mazars-automation/bloodhound-automation/src/project.py", line 16, in <module>
    class Project:
  File "/home/adrien/mazars-automation/bloodhound-automation/src/project.py", line 224, in Project
    def extractZip(self, zip_file: str) -> list[str]:
TypeError: 'type' object is not subscriptable
```

Using Python 3.8.10

**Comment by Tanguy-Boisset** [comment]
This error happens when using Python < 3.9, I've just pushed a fix on master 5dbf979a9da218e3db4589dd339ff09e37d896cc
